---
- name: Install Jenkins on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Disable unattended-upgrades
      command: systemctl stop unattended-upgrades

    - name: Wait for the dpkg lock to be released
      command: "while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done"

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins apt repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Update apt package index after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Allow traffic on port 8080
      command: ufw allow 8080/tcp

    - name: Reload UFW to apply changes
      command: ufw reload
      when: ansible_facts['os_family'] == 'Debian'

    - name: Re-enable unattended-upgrades
      command: systemctl start unattended-upgrades
