---
- name: Install Metasploit Framework
  hosts: all
  become: yes
  tasks:

    - name: Install dependencies
      apt:
        name:
          - curl
          - gnupg2
          - postgresql
          - postgresql-contrib
        state: present
        update_cache: yes

    - name: Add Metasploit repository signing key
      apt_key:
        url: https://apt.metasploit.com/metasploit-framework.gpg.key
        state: present

    - name: Add the Metasploit repository
      apt_repository:
        repo: "deb http://apt.metasploit.com/ bionic main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Metasploit Framework
      apt:
        name: metasploit-framework
        state: present

    - name: Initialize Metasploit Database
      shell: msfdb init
      args:
        executable: /bin/bash
