---
- name: Clean up duplicate Google Chrome apt sources
  hosts: all
  become: yes
  tasks:
    - name: Remove duplicate Google Chrome apt sources
      lineinfile:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list
        - /etc/apt/sources.list.d/google-chrome.list
      ignore_errors: yes

    - name: Update apt cache
      apt:
        update_cache: yes



- name: Install Metasploit Framework
  hosts: all
  become: yes
  tasks:

    - name: Install dependencies
      apt:
        name:
          - curl
          - gnupg2
          - postgresql
          - postgresql-contrib
          - wget
          - git
          - build-essential
          - libreadline-dev
          - libssl-dev
          - zlib1g-dev
          - libsqlite3-dev
          - libpq-dev
        state: present
        update_cache: yes

    - name: Download and Install RVM (Ruby Version Manager)
      shell: |
        apt-add-repository -y ppa:rael-gc/rvm
        apt-get update
        apt-get install -y rvm
        source /etc/profile.d/rvm.sh
        rvm install ruby --default
      args:
        executable: /bin/bash

    - name: Download Metasploit Framework
      git:
        repo: https://github.com/rapid7/metasploit-framework.git
        dest: /opt/metasploit-framework

    - name: Install required Ruby gems for Metasploit
      shell: |
        cd /opt/metasploit-framework
        gem install bundler
        bundle install
      args:
        executable: /bin/bash

    - name: Create symbolic link to msfconsole
      file:
        src: /opt/metasploit-framework/msfconsole
        dest: /usr/local/bin/msfconsole
        state: link

    - name: Initialize Metasploit Database
      shell: msfdb init
      args:
        executable: /bin/bash
